language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist --verbose

after_script:
  - php vendor/bin/coveralls -v
